{% set name = "napari-workflow-optimizer" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-workflow-optimizer-{{ version }}.tar.gz
  sha256: e756ab013740cdc89fbb2626291386579ec8ce30ec30153a1b79517d7790f9c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer
    - napari-workflows
    - numpy
    - pyclesperanto-prototype
    - python >={{ python_min }}
    - scikit-learn
    - scipy

test:
  imports:
    - napari_workflow_optimizer
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-workflow-optimizer
  summary: Optimize image processing workflows in napari for segmentation quality
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
